# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zqlite-0.0.1-RWLaY64xnAAxsD2YNT8QqPMJUuaFv2GOzFRR4aGypJv3";
    path = fetchgit {
      url = "https://github.com/karlseguin/zqlite.zig";
      rev = "5ac4cabe95a6d7faa7baf0da8057a8e6e8a227a1";
      hash = "sha256-gdYleac8guMRLmDgIko2nL9e6U2pbFU1mKc79OknImI=";
    };
  }
]
